### ISSUE TITLE
mediamosa/content/asset page segfaults after commit ba4bc3c

### ISSUE THREAD

**Issue by flyapen** [mediamosa/mediamosa#219]
Mediamosa is generating a segfault on mediamosa/content/asset page from commit ba4bc3c onwards. Possible that other pages have the same problem.

Found out that the issue is related to the SOLR changes, if you change the search engine from default to SOLR ( even without solr configured ) the problem is resolved and the page loads "correctly".

**Comment by rblanker** [comment]
See fix in e1f0515c67e509dbaa6b2f747fb9c05e9f94b4ca.

**Comment by flyapen** [comment]
just tested this and works as expected
