### ISSUE TITLE
is_hinted=true is missing

### ISSUE THREAD

**Issue by sajkec** [mediamosa/mediamosa#232]
In the older version of mediamosa, after the files would be analysed and transcoded there would be parameter set as "is_hinted=true". 

My questions:
1) What is the purpose of this parameter?
2) I have tested today's version from git, and "is_hinted" is not set after successful analyse and transcode of the files. Has this feature been removed?

**Comment by rblanker** [comment]
The is_hinted was an old option in mp4box executable that is no longer used. The old mpeg and flv files need 'hinting' to allow streaming (changing the play position while streaming). That is all gone now we are newer codecs. Will migrate this out of the code at some point, you can ignore the setting.

**Comment by sajkec** [comment]
Thanks for explanation, closing issue.
