### ISSUE TITLE
Still job priority

### ISSUE THREAD

**Issue by sajkec** [mediamosa/mediamosa#233]
When uploading new video, if there are other jobs running (but open slots are available), it will happen that transcode job will start before still jobs does - not sure why, and this does not happen always. This will cause still to wait until transcode is done - why they can't run in paralel? 

Our main issue is, that we do two stills for the video (smaller and larger preview) and if transcode will start before still job, the "default" still will become the larger (later in job queue) one and the preview on portal will be incorrect.

**Comment by rblanker** [comment]
What you can do is creating own job server for stills (and remove still generation on other job servers), then the still is created as soon it has free slots on that jobserver. Because stills do not take a lot of resources like transcoding, you can assign some slots to this still jobserver. I do not know your setup, and myself do not maintain MM setups these days. What version MM are you using atm?

**Comment by sajkec** [comment]
I run the latest version 3.6.1 (build 2207), with two transcode servers (both with selected still generation). I might try setup separate job server just for still if this will help. Probably analyse job should be on this separate server too? - leaving only transcoding

**Comment by sajkec** [comment]
I did simple test, since i have two job server. I unchecked ffmpeg on first one, and run the test and analyse, still on the other. I uploaded 3 videos, first two were ok, the last one had the same issue as before:
1. analyse
2. initial transcode
3. initial still lq + hq ... the default was again set on wrong

So looks like your suggestion will not work.

**Comment by rblanker** [comment]
Analyse is done right after the upload, so you can ignore that. The analyse job setting is only when analyse is run by manually triggering it using REST call f.e.

In what way are you generating lq and hq version of the still? The default value on the still depends on which one is generated first, but you already knew that. The job has an priority setting, but I'm unsure if that can be easily set, depends how you trigger the HQ version.

**Comment by sajkec** [comment]
We trigger still job via rest. One (first) rest call for lq, and another for hq. But what i think is that both get in the queue and both jobs are "in progress" in parallel. 

This code is in our sistem from the mediamosa version 2.x, where it worked one still quality at the time - now it's in parallel.

Is there a REST parameter for /asset/*/still/create, that would mark first still Default?

**Comment by rblanker** [comment]
There is a parameter called 'priority', it is set to 100. Provided it higher for LQ than 100 might fix your problem.

**Comment by sajkec** [comment]
The priorities do help, but they work in reverse. Anyway, hope this helps someone with the same issue, our priority setup (priority = number beside the job description) for two job server setup. This will trigger jobs by priority from top to bottom. 

> Create stills:
> still hq | 19
> still lq | 20
> Transcode:
> job 480p | 30
> job 360p | 40
> job 720p | 50
> job 1080p | 60
> job 1440p | 70
> job 2180p | 80

What is nice about this setup is that if you upload a lot of videos to fill the queue, the 480p jobs will always be first in the queue, followed by 360p, 720p... Just keep in mind the job timeout, when you have busy server, as higher resolutions might take a lot of time to finish.
