### ISSUE TITLE
create manifest file

### ISSUE THREAD

**Issue by sajkec** [mediamosa/mediamosa#235]
We would like to make a step forward to adaptive streaming for VOD files, which requires creation of some sort of manifest file. 

- My first issue are the multiple input files, which at least in basic setup have some random names ,and for manifest it's best if they are in the same folder. Can we configure mediamosa to create some more readable names based on original mediafile? how? 

My example would be: 
> Original: A1OYXRKdgXSIojahJesdV7aI
> 360p: A1OYXRKdgXSIojahJesdV7aI_360p
> 480p: A1OYXRKdgXSIojahJesdV7aI_480p
> 720p: A1OYXRKdgXSIojahJesdV7aI_720p
> ...

- can we use mediamosa to create such manifest file? FFMpeg can be used for this, an here is example command:
`ffmpeg  -i video1.webm -i video2.webm .... manifest.mpd`

**Comment by rblanker** [comment]
Yes, you can, but not without writing own code. You could hook into still generation, to generate this manifest, but it will not be easy coding, but it does provide some basis to execute the ffmpeg line, and generate a mediafile holding the manifest file. But that is just from the top of my head. In the end you might need to add your own tool (module) for this and somehow hook into the mediafile generation.

**Comment by sajkec** [comment]
what about transcoding naming? is it possible to set so that transcoded version have original mediafile in their naming convention?

**Comment by sajkec** [comment]
@rblanker any tips on the naming options - to have all mediafiles for the asset use the same naming prefix? i tried to play with different hash settings inside vpx files, but i just messed all up.
